import nonselfadjoint_sub_algebras_algebras_involution_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace nonselfadjoint_sub_algebras_algebras_involution_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end nonselfadjoint_sub_algebras_algebras_involution_theorem_canonical_lane_mathlib
end HautevilleHouse
